### ISSUE TITLE
Need more labels for filtering

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#13]
Since we are using the labels to obtain information about the instances, we will need these labels applied based on the state of the instance. 

**Shelved**: if the instance is shelved (by user or by timeout limit)
**Online**: if the instance is online/running
**Error**: if the instance is in the errored state in Exosphere. This happens when there is a JS2 issue, like the instance is showing online but in an inaccessible state.

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/8a6137e1988d4cd4243b816db8f3d7a4b0f38a22

`status:` labels for each possible server status[^1] have been added in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/08fb974677c64ce631c8aa4e49999aa98e89cd50, then a workflow running every 5 minutes (the maximum frequency) has been added to query the list of servers using `openstack` and update each issues accordingly.

[^1]: https://docs.openstack.org/api-guide/compute/server_concepts.html#server-status

**Comment by jcfr** [comment]
Additionally, the label `instance:approved` has been renamed to `request:approved`, and the label `instance:created` has been removed in favor of the new `status:*` labels.

**Comment by jcfr** [comment]
After identifying issue with the workflow "Update Request Status Label", I temporarily disabled it.

![image](https://github.com/user-attachments/assets/8ca9bcbf-2760-43bd-a62a-16123d1da921)
![image](https://github.com/user-attachments/assets/ddbc1767-4f32-4f89-a1d2-815ae141107b)

Once the workflow is updated to avoid both removing and re-adding the same label, it will be re-enabled.
