### ISSUE TITLE
Disable ubuntu software update

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#23]
Instances that are online 1-2 days trigger the ubuntu software update, which sometimes brings in libraries/packages that break the functioanalit. Let's disable that, particularly there will be no need for it when we switch to creating instances from scratch everytime. 

![image](https://github.com/user-attachments/assets/64724400-ab8d-4613-b898-5633d7aa09a2)

**Comment by jcfr** [comment]
Fixed in those commites:
* https://github.com/MorphoCloud/exosphere/commit/f8640dca1a9d83eff5fc3f341abb2ee752ceecf0
* https://github.com/MorphoCloud/exosphere/commit/c0c274deec732bd3fae393f5b81009db70456db6

It disabled the following:
* Unattended upgrades
* Release upgrade
* Package updates

and also ensure that the following processes are not running when connecting to the instance:

```
/bin/sh -c /usr/lib/ubuntu-release-upgrader/check-new-release-gtk
/usr/bin/python3 /usr/lib/ubuntu-release-upgrader/check-new-release-gtk
```

References:
* https://linuxconfig.org/disable-automatic-updates-on-ubuntu-22-04-jammy-jellyfish-linux
* https://help.ubuntu.com/community/Upgrades#Upgrade_policy
