### ISSUE TITLE
Logs for runner

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#48]
Instance runner is running out of HD space. it appears it has been set up with 30GB of storage. We have two options:

1. increase the boot storage volume (100GB?)
2. actually keep the original boot volume size (20GB). Create a dedicated share for logs. attached the share to the instance and move the logs periodically to the share for achiving.

**Comment by jcfr** [comment]
To follow-up, 
- I manually cleaned up the temp directories taking spaces. Available spaces is now 
- Now that the fix for the problematic GitHub action has been integrated (https://github.com/s0/git-publish-subdir-action/pull/106), I am now working on updating the corresponding workflow

Before:

```
Filesystem       Size  Used Avail Use% Mounted on
/dev/sda1        29G 29G     0 100% /
```

After:

```
Filesystem       Size  Used Avail Use% Mounted on
/dev/sda1        29G   22G  7.8G  73% /
```

**Comment by jcfr** [comment]
Fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/bf6706823e97bdfd39a124efe9627dbbc1bce9b4

**Comment by jcfr** [comment]
Deployed through https://github.com/MorphoCloud/MorphoCloudInstances/commit/1a6e47de37e2803dca9f2a031d1eb238a35b281a
