### ISSUE TITLE
email obfuscation problem

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#56]
Emails fail for Sara's instances:

https://github.com/MorphoCloud/MorphoCloudInstances/issues/73

https://github.com/MorphoCloud/MorphoCloudInstances/issues/71

Also she needs to be added to the admin team (she can't approve instances).

**Comment by jcfr** [comment]
* Encoding of email fixed in https://github.com/MorphoCloud/MorphoCloudWorkflow/commit/0f35a2972567154ac66d9325ca19f72ba0203407 and deployed through https://github.com/MorphoCloud/MorphoCloudInstances/commit/99867486615e3ca34e6e729c6b380779dbd2f485

* Setup of @smrolfe as admin by updating repository variables `MORPHOCLOUD_GITHUB_ADMINS` and `MORPHOCLOUD_GITHUB_ADMIN_EMAILS`
